config/routes.rb
Rails.application.routes.draw do
  resources :people do
    patch :update_status, on: :member
  end



  resources :clients do
    patch :update_status, on: :member
  end

  post 'clients/page', to: "clients#page"




  
  get 'search',to: "clients#search"
  post 'users/sort',to: "clients#sortusers"
  post 'emails/sort',to: "clients#sortemails"
  post 'status/sort',to: "clients#sortstatus"


  devise_for :users, :skip => [:registrations], controllers: { sessions: 'sessions' }
  devise_scope :user do
    authenticated :user do
      root 'admin/admin#dashboard', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   # Singular resource for the Profile model

   get 'profile/edit', to: 'admin/admin#edit_profile', as: :edit_profile
   patch 'profile', to: 'admin/admin#update_profile', as: :profile
   get 'project' , to: 'admin/admin#project_management'
   get 'news' , to: 'admin/admin#news_management'

  end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  before_action :authenticate_user!
  before_action :set_person, only: %i[ show edit update destroy ]

  include Pagination

  POSTS_PER_PAGE = 6

  def index
    @pagination, @people =  paginate(collection:Person.all, params: page_params)
  end



  # GET /people/1 or /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to person_url(@person), notice: "User was created successfully." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to person_url(@person), notice: "Successfully updated." }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_status
    @person = Person.find(params[:id])
    @person.update(status: @person.status==true ? false : true)
    redirect_to people_path
  end
  

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url, notice: "Deleted successfully." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:first_name, :last_name, :email, :phone)
    end

    def page_params
      params.permit(:page).merge(per_page: POSTS_PER_PAGE)
    end
 
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_with(model: person) do |form| %>
  <% if person.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/people/_pagination.html.erb
<div class="d-flex justify-content-center">
  <% if  pagination.previous_page? %>
    <%= link_to 'First', people_path(page: 1), class: "btn btn-outline-secondary me-2" %>
    <%= link_to '< Previous', people_path(page: pagination.previous_page), class: "btn btn-outline-secondary me-4" %>
  <% else %>
    <span class="btn btn-outline-secondary me-2 disabled">First</span>
    <span class="btn btn-outline-secondary me-4 disabled">&#60; Previous</span>
  <% end %>
  <p class="mt-2"><%= "Page #{pagination.page} of #{pagination.total_pages}" %></p>
  <% if pagination.next_page? %>
    <%= link_to 'Next >', people_path(page: pagination.next_page), class: "btn btn-outline-secondary ms-4 me-2" %>
    <%= link_to 'Last', people_path(page: pagination.total_pages), class: "btn btn-outline-secondary ms-2" %>
  <% else %>
    <span class="btn btn-outline-secondary ms-4 me-2 disabled">Next &#62;</span>
    <span class="btn btn-outline-secondary ms-2 disabled">Last</span>
  <% end %>
</div>

app/views/people/_person.html.erb
<div id="<%= dom_id person %>">
  <p>
    <strong>First name:</strong>
    <%= person.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= person.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= person.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= person.phone %>
  </p>

</div>

app/views/people/edit.html.erb
<div class="position-relative d-flex p-0" id="top">
        <!-- Spinner Start -->
        <div id="spinner"
            class="show bg-light position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only"></span>
            </div>
        </div>
        <!-- Spinner End -->
        <%= render partial: "shared/sidebar"%>

        <!-- Content Start -->
        <div class="content pb-3">
            
         <%= render partial: "shared/navbar" %>

            <!-- Start Content -->
          <!-- Start Content -->
            <div class="container-fluid py-2 px-3 mt-3">
                <div class="card-panel bg-white p-4 radius-10">

                    <div class="card mx-auto" style= "width:25rem;">
                        <div class="card-header">
                          <h3>Edit User</h3>
                        </div>
                        <div class="card-body">

                          <%= render "form", person: @person %>
                          <br>
                          <div>
                          <%= link_to "Show", @person,class:"btn btn-outline-dark"  %> |
                          <%= link_to "Back", people_path  ,class:"btn btn-outline-dark" %>
                          </div>
                        </div>
                    </div>


                </div>
            </div>

        </div>
                      
        <!-- End Content  -->
    </div>

app/views/people/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="position-relative d-flex p-0" id="top">
        <!-- Spinner Start -->
        <div id="spinner"
            class="show bg-light position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only"></span>
            </div>
        </div>
        <!-- Spinner End -->
        <%= render partial: "shared/sidebar"%>

        <!-- Content Start -->
        <div class="content pb-3">
            
         <%= render partial: "shared/navbar" %>

            <!-- Start Content -->
          <!-- Start Content -->
            <div class="container-fluid py-2 px-3 mt-3">
                <div class="card-panel bg-white p-4 radius-10">

                    <div class="d-flex flex-wrap justify-content-between align-items-center page-header">
                        <h1 class="h2 mb-2">User Management(Frontend)</h1> 
                    </div>
                    

                    <div class="card" >
                      <div class="card-body">
                        <table class="table  table-striped table-bordered table-hover">
                          <div class="row m-3">
                            <form class="m-4 mb-0">
                              <div class="form-row">
                              <div class="col m-4">
                              <input class="form-control mr-sm-2" id="search1" placeholder="Type to search...">
                              </div>
                            
                              </div>
                            </form>

                          
                        </div>
                        <br/>
                        <thead class="thead-light">
                            <th>Name &nbsp;<i class="fa-sharp fa-solid fa-sort"></i></th>
                            <th>Email &nbsp;<i class="fa-sharp fa-solid fa-sort"></i></th>
                            <th>Status &nbsp;<i class="fa-sharp fa-solid fa-sort"></i></th>
                            <th colspan ="4" style="text-align: center;">actions </th>

                        </thead>
                        <tbody id = "datalist1">
                            <% @people.each do |person| %>
                              <tr>
                                  <td><%= person.first_name + " "+ person.last_name%></td>
                                  <td><%= person.email%></td>
                                  <td><%= person.status == true ? 'Active' : 'Inactive'%></td>
                                   <td><% if person.status %>
                                        <%= link_to "",  update_status_person_path(person),data:{'turbo-method': :patch}, class: "fa fa-lock-open text-decoration-none", style:"color: green;" %>
                                      <% else %>
                                        <%= link_to "", update_status_person_path(person),data:{'turbo-method': :patch}, class: "fa fa-lock text-decoration-none", style:"color: red;" %>
                                      <% end %>
                                    </td>
                                  <td style="text-align: center;"><%= link_to "", person,class:"fa-regular fa-eye text-decoration-none" %></td>
                                  <td style="text-align: center;"><%= link_to "",edit_person_path(person),class:"fa-solid fa-pencil text-decoration-none" %></td>
                                  <td style="text-align: center;"><%= link_to "",person,data:{turbo_method: :delete,
                                      turbo_confirm: 'Are you sure?'}, class: "fa-sharp fa-solid fa-trash"%></td>
                              </tr>
                            <% end %>     
                        </tbody>
                        </table>
                        <br>

                        <%= link_to "", new_person_path ,class:"fa-solid fa-user-plus"%>
                        <br/>
                        <br/>
    
                      </div>
                      <%= render partial: 'pagination', locals: { pagination: @pagination } %>
                    
                      </div>
                    
                      </div>

                </div>

              </div> 
        <!-- End Content  -->

    </div>
  

  <script>
  $(document).ready(function() {
    $('th:eq(0)').click(function() {
      var rows = $('#datalist1').find('tr').get();
      rows.sort(function(a, b) {
        var nameA = $(a).find('td:eq(0)').text().toUpperCase();
        var nameB = $(b).find('td:eq(0)').text().toUpperCase();
        return nameA.localeCompare(nameB);
      });
      $.each(rows, function(index, row) {
        $('#datalist1').append(row);
      });
    });
  });


  $(document).ready(function() {
    $('th:eq(1)').click(function() {
      var rows = $('#datalist1').find('tr').get();
      rows.sort(function(a, b) {
        var nameA = $(a).find('td:eq(1)').text().toUpperCase();
        var nameB = $(b).find('td:eq(1)').text().toUpperCase();
        return nameA.localeCompare(nameB);
      });
      $.each(rows, function(index, row) {
        $('#datalist1').append(row);
      });
    });
  });


  $(document).ready(function(){
  $("#search1").on("keyup", function() {
    var value = $(this).val().toLowerCase();
    $("#datalist1 tr").filter(function() {
      $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
    });
  });
});
 
</script>

app/views/people/new.html.erb
<div class="position-relative d-flex p-0" id="top">
        <!-- Spinner Start -->
        <div id="spinner"
            class="show bg-light position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only"></span>
            </div>
        </div>
        <!-- Spinner End -->
        <%= render partial: "shared/sidebar"%>

        <!-- Content Start -->
        <div class="content pb-3">
            
         <%= render partial: "shared/navbar" %>

            <!-- Start Content -->
            <div class="container-fluid py-2 px-3 mt-3">
                <div class="card-panel bg-white p-4 radius-10">

                    <div class="d-flex flex-wrap justify-content-between align-items-center page-header">
                       <div class="card mx-auto" style= "width:25rem;">
                        <div class="card-header">
                          <h3>New User</h3>
                        </div>
                        <div class="card-body">
                          <%= render "form", person: @person %>
                           <br>
                        <div>
                          <%= link_to "Back", people_path , class:"btn btn-outline-dark" %>
                        </div>
                      </div>

                    </div>
                </div>

            </div>


            

        </div>
                      
        <!-- End Content  -->
    </div>

app/views/people/show.html.erb
<div class="position-relative d-flex p-0" id="top">
        <!-- Spinner Start -->
        <div id="spinner"
            class="show bg-light position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only"></span>
            </div>
        </div>
        <!-- Spinner End -->
        <%= render partial: "shared/sidebar"%>

        <!-- Content Start -->
        <div class="content pb-3">
            
         <%= render partial: "shared/navbar" %>

            <!-- Start Content -->
          <!-- Start Content -->
            <div class="container-fluid py-2 px-3 mt-3">
                <div class="card-panel bg-white p-4 radius-10">
                        <div class="card">
                        <div class="card-body">
                          <h2 class="card-title"> <%= @person.first_name %>
                            <%= @person.last_name %>  </h2>
                            <h5 class="card-subtitle mb-2 text-muted"> <%= @person.email %>   |     <%= @person.phone %></h5>
                            <br/>
                            <br/>
                        <div>
                          <%= link_to "Edit", edit_person_path(@person) ,class:"btn btn-outline-dark"%> |
                          <%= link_to "Back", people_path,class:"btn btn-outline-dark"  %>

                        </div>

                    </div>

                </div>
                      


            </div>
          </div>

        </div>
                      
        <!-- End Content  -->
    </div>