config/routes.rb
Rails.application.routes.draw do
  resources :people do
    patch :update_status, on: :member
  end



  resources :clients do
    patch :update_status, on: :member
  end

  post 'clients/page', to: "clients#page"




  
  get 'search',to: "clients#search"
  post 'users/sort',to: "clients#sortusers"
  post 'emails/sort',to: "clients#sortemails"
  post 'status/sort',to: "clients#sortstatus"


  devise_for :users, :skip => [:registrations], controllers: { sessions: 'sessions' }
  devise_scope :user do
    authenticated :user do
      root 'admin/admin#dashboard', as: :authenticated_root
    end
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   # Singular resource for the Profile model

   get 'profile/edit', to: 'admin/admin#edit_profile', as: :edit_profile
   patch 'profile', to: 'admin/admin#update_profile', as: :profile
   get 'project' , to: 'admin/admin#project_management'
   get 'news' , to: 'admin/admin#news_management'

  end

app/views/shared/_navbar.html.erb
<!-- Navbar Start -->
            <nav class="navbar navbar-expand navbar-dark px-3 px-lg-4 py-3 top_header">
                <a class="sidebar-toggler flex-shrink-0 me-2 d-lg-none">
                    <img src="<%= asset_path('icons/hamburger_icon.svg') %>" alt="" width="30" />
                </a>

               <div class="d-none d-md-block title_hd">
                  <% if current_user && current_user.profile %>
                    <span class="h6 mb-0 text-capitalize">Hello <%= current_user.profile.first_name.present? ? current_user.profile.first_name : 'Admin' %></span>
                  <% else %>
                    <span class="h6 mb-0 text-capitalize">Hello Admin</span>
                  <% end %>
                   <%# <a class="d-block f-small text-mute"><%= Time.now.strftime('%A, %B %d, %Y %I:%M %p') %></a> 
                </div>


                <div class="navbar-nav align-items-center ms-auto">
                    <div class="nav-item">
                      <% if current_user.profile.present? && current_user.profile.image.present? %>
                      <em class="me-2 avtar avtar-30 border-0">
                        <%= link_to image_tag(current_user.profile.image, alt: "", width: "30"), edit_profile_path %>
                      </em>
                    <% else %>
                      <%= link_to edit_profile_path do %>
                           <em class="me-2 avtar avtar-30 border-0"><%= image_tag asset_path('profile.png', alt:"" ,width:"30") %></em>
                         <%end%>
                    <% end %>




                       
                    </div>

                </div>
            </nav>
<!-- Navbar End -->

app/views/shared/_sidebar.html.erb
<!-- Sidebar Start -->

<aside class="sidebar pb-3">
            <button class="d-lg-none close_btn"><img src="<%= asset_path('icons/close_icon.svg') %>" alt="Close" width="30" /></button>
            <nav class="navbar text-left">
                <a href="<%= authenticated_root_path%>" class="navbar-brand my-4 pt-2 pb-4 m-auto text-center">
                   <img src="<%= asset_path('logo.svg') %>" alt="Sbrigit" width="144" class="img-fluid" />
                </a>

                <ul class="navbar-nav w-100">
                    <li><a href="<%= authenticated_root_path%>" class="nav-link"><i class="me-2"><img
                                    src="<%= asset_path('icons/menu_icons/dashboard_icon.svg') %>" width="24" alt="" /></i> Dashboard </a></li>
                     <li class="nav-item">
                       <%= link_to news_path, class: "nav-link" do %>
                        <i class="me-2">
                            <%= image_tag("icons/menu_icons/retailor_icon.svg", width: 23) %>
                        </i>
                        News 
                        <% end %>
                    </li>
                    <li><%= link_to project_path, class: "nav-link" do %>
                        <i class="me-2">
                            <%= image_tag("icons/menu_icons/driver_icon.svg", width: 23) %>
                        </i>
                        Project 
                        <% end %>
                    </li>
                   <li class="nav-item">
                       <%= link_to clients_path, data: { turbo: false }, class: "nav-link" do %>
                        <i class="me-2">
                            <%= image_tag("icons/menu_icons/retailor_icon.svg", width: 23) %>
                        </i>
                        User Management
                        <% end %>
                    </li>

                    <li class="nav-item">
                       <%= link_to people_path, class: "nav-link" do %>
                        <i class="me-2">
                            <%= image_tag("icons/menu_icons/retailor_icon.svg", width: 23) %>
                        </i>
                        Users
                        <% end %>
                    </li>

                </ul>
                 <div class="logout_menu">
                   <%= link_to destroy_user_session_path, 'data-turbo-method': :delete, class: "nav-link" do %>
                      <i class="me-2"><%= image_tag('icons/menu_icons/logout_icon.svg', width: '24', alt: 'Logout') %></i>
                                   Log Out
                     <% end %>
                </div>
               
            </nav>

        </aside>
<!-- Sidebar End -->